### ISSUE TITLE
Conteúdo mirror sobre

### ISSUE THREAD

**Issue by Pquar** [eduardadomanski/mirror-feshion-#1]
```html
<html>
        <head>
                <meta charset="utf-8">
                <title>Sobre a Mirror Fashion</title>

                <link rel="stylesheet" href="css/sobre.css">
        </head>

        <body>
                <img src="img/logo.png">

                <h1>A Mirror Fashion</h1>
                <p>
                        A <strong>Mirror Fashion</strong> é a maior empresa comércio eletrônico no segmento de moda em todo o mundo. 
                        Fundada em 1932, possui filiais em 124 países, sendo líder de mercado com mais de 90% de 
                        participação em 118 deles.
                </p>

                <p>
                        Nosso centro de distribuição fica em <a href="https://maps.google.com.br/?q=Jacarezinho">Jacarezinho, no Paraná</a>. De lá, saem 48 aviões que distribuem nossos produtos às casas do mundo todo. Nosso centro de distribuição:
                </p>

                <figure>
                        <img src="img/centro-distribuicao.png">
                        <figcaption>Centro de distribuição da Mirror Fashion</figcaption>
                </figure>

                <p>
                        Compre suas roupas e acessórios na Mirror Fashion. Acesse <a href="index.html">nossa loja</a> ou entre em contato 
                        se tiver dúvidas. Conheça também nossa <a href="#historia">história</a> e nossos <a href="#diferenciais">diferenciais</a>.
                </p>

                <h2 id="historia">História</h2>

                <figure id="familia-pelho" >
                        <img src="img/familia-pelho.jpg">
                        <figcaption>Família Pelho</figcaption>
                </figure>

                <p>
                        A fundação em 1932 ocorreu no momento da descoberta econônica do interior do Paraná. A 
                        família Pelho, tradicional da região, investiu todas as suas economias nessa nova iniciativa, 
                        revolucionária para a época. O fundador <em>Eduardo Simões Pelho</em>, dotado de particular visão 
                        administrativa, guiou os negócios da empresa durante mais de 50 anos, muitos deles ao lado 
                        de seu filho <em>E. S. Pelho Filho</em>, atual CEO. O nome da empresa é inspirado no nome da família.
                </p>

                <p>
                        O crescimento da empresa foi praticamente instantâneo. Nos primeiros 5 anos, já atendia 18 países. 
                        Bateu a marca de 100 países em apenas 15 anos de existência. Até hoje, já atendeu 740 milhões 
                        de usuários diferentes, em bilhões de diferentes pedidos.
                </p>

                <p>
                        Dada a importância econômica da empresa para o Brasil, a família Pelho já recebeu diversos prêmios, 
                        homenagens e condecorações. Todos os presidentes do Brasil já visitaram as instalações da Mirror 
                        Fashion, além de presidentes da União Européia, Ásia e o secretário-geral da ONU.
                </p>

                <h2 id="diferenciais">Diferenciais</h2>

                <ul>
                          <li>Menor preço do varejo, garantido</li>
                          <li>Se você achar uma loja mais barata, leva o produto de graça</li>
                          <li>Maior comércio eletrônico de moda do mundo</li>
                          <li>Atendimento via telefone, email, chat, twitter, facebook, carta, fax e telegrama</li>
                          <li>Presente em 124 países</li>
                          <li>Mais de um milhão de funcionários em todo o mundo</li>
                </ul>

                <div id="rodape">
                    <img src="img/logo.png">
                    &copy; Copyright Mirror Fashion
                </div>
        </body>
</html>
```
```css
body {
        color: #333333;
        font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
        margin-left: auto;
        margin-right: auto;
        width: 940px;
}

h1 {
        background-image: url(../img/sobre-background.jpg);
        padding: 10px;
}

h2 {
        border-bottom: 2px solid #333333;
        margin-top: 30px;
}

figure {
        background-color: #F2EDED;
        border: 1px solid #ccc;
        text-align: center;
        padding: 15px;
        margin: 30px;
}

figcaption {
        font-style: italic;
        margin-top: 10px;
}

p {
        padding: 0 45px;
        text-indent: 15px;
}

#centro-distribuicao {
        margin-left: auto;
        margin-right: auto;
        width: 550px;
}

#rodape {
        color: #777;
        margin: 30px 0;
        padding: 30px 0;
}

#rodape img {
        margin-right: 30px;
        vertical-align: middle;
        width: 94px;
}

#familia-pelho {
        float: right;
        margin: 0 0 10px 10px;
}
```
